### ISSUE TITLE
##CC not working

### ISSUE THREAD

**Issue by andrepetinga** [tomolimo/mailbehaviours#1]
Hello!
I just installed the plugin and, so far:

##from - Works fine!

##CC - is not working. I've tested several times and it just doesn't do anything. I tried with only this tag and even tried the two tags in same email. ##From did it's job, but ##CC did not...

Looking at the code it seems in ##from you search for email and then Name. But in the #CC you are not lookin for email, just name. Am I right?

**Comment by tomolimo** [comment]
Hello @andrepetinga 
Exactly, I've just checked the process, and I'm not doing the same process for the ##From and the ##CC.
I'm going to fix this asap.
Thank you
Regards,
Tomolimo

**Comment by tomolimo** [comment]
See: https://github.com/tomolimo/mailbehaviours/releases/tag/1.0.1
