### ISSUE TITLE
Uncaught Exception TypeError: Argument 1 passed to MailCollector::getHeaders() must be an instance of Laminas\Mail\Storage\Message, string given

### ISSUE THREAD

**Issue by mart1** [tomolimo/mailbehaviours#10]
Hi,

With GLPI 9.5.3 and Mailbehaviours 1.0.3, when the mail collector find a mail with ##From, it crashs with:

CRITICAL:   *** Uncaught Exception TypeError: Argument 1 passed to MailCollector::getHeaders() must be an instance of Laminas\Mail\Storage\Message, string given, called in [...]/plugins/mailbehaviours/hook.php on line 171 in [...]/mailcollector.class.php at line 1406
  Backtrace :
  plugins/mailbehaviours/hook.php:171                MailCollector->getHeaders()
  inc/plugin.class.php:1350                          PluginMailBehaviours::plugin_pre_item_add_mailbehaviours()
  inc/commondbtm.class.php:1093                      Plugin::doHook()
  inc/mailcollector.class.php:821                    CommonDBTM->add()
  front/mailcollector.form.php:88                    MailCollector->collect()

**Comment by tomolimo** [comment]
Hello @mart1 
Could you apply the patches like explained for release 1.0.2 and for GLPI 9.5.3?
See here: https://github.com/tomolimo/mailbehaviours/releases/tag/1.0.2
Thank you,
Regards,
Tomolimo
