### ISSUE TITLE
Plugin for GLPI 10

### ISSUE THREAD

**Issue by ghost** [tomolimo/mailbehaviours#11]
Hello,

this plugin still working for GLPI 10 ?

thank you

**Comment by tomolimo** [comment]
Hello @stdglpi 
This plugin is not yet compatible with GLPI 10.0
Sorry, you'll have to wait for the release :)
Or you may propose a PR,
Thank you
Regards,
Tomolimo

**Comment by tomolimo** [comment]
Hello @stdglpi 
Thanks to @triangle-z, it is solved by release 2.0.0: https://github.com/tomolimo/mailbehaviours/releases/tag/2.0.0
Thank you,
Regards,
Tomolimo

**Comment by ghost** [comment]
Hello @tomolimo  

When I transfert an email and I add **##** in front of **From**, in GLPI, i'm the owner of the ticket.
Same if I add ##CC
Do you think it's a problem with a rule ?

I use GLPI [GLPI 10.0.2](http://glpi-project.org/)

![image](https://user-images.githubusercontent.com/63521311/181465897-3dc174d1-75da-4812-a921-e928d8b2972d.png)

**Comment by tomolimo** [comment]
Hello @stdglpi 
If you have an issue with the 10.0 compliant release, please create a new issue and do not mix several topics in the same issue.
Thank you
Regards,
Tomolimo
