### ISSUE TITLE
Not sure if it's a bug, but sometimes the plugin doesn't work

### ISSUE THREAD

**Issue by andrepetinga** [tomolimo/mailbehaviours#17]
Hello @tomolimo.
I've been using this plugin for a long time, and now I noticied that, sometimes, the plugin doesn't work!
I got the alert from a colleague saying it isn't working.
And I just tested it, and I can confirm that, sometimes, it really doesn't work!!

I made the tests on 2 servers (production and quality assurance) and the results were the same.
Looking at our email, yesterday someone used it and it worked!!

Any idea?
How can I debug this?

Regards,
André Petinga

**Comment by tomolimo** [comment]
Hello @andrepetinga 
Could you give more information about versions (GLPI, Plugin, ...), and about the steps to reproduce the issue when "it doesn't work"?
Thank you,
Regards,
Tomolimo

**Comment by andrepetinga** [comment]
GLPI 10.0.12 (production) and GLPI 10.0.16 (quality assurance)
In both cases, the version of the plugin is 2.0.0

The steps I'm doing to test, were the same as always:
I opened an email (random one), forward to the email configured on GLPI, deleted my signature and wrote ##from:email_from_another_person@our_domain

And when the ticket was created, the requester was my email and not the one I wrote after the ##from:

Regards,
André Petinga

**Comment by tomolimo** [comment]
Hello @andrepetinga 
Did you check that the user email was existing in GLPI?
Did you check that the user was active and not deleted?
Did you check that the user has rights to create tickets into an existing entity?
Thank you,
Regards,
Tomolimo

**Comment by andrepetinga** [comment]
> Hello @andrepetinga
> Did you check that the user email was existing in GLPI?
> Did you check that the user was active and not deleted?
> Did you check that the user has rights to create tickets into an existing entity?


Hello. Yes, to all...

I asked the colleague who used it this week and worked well, to send some test emails to our quality assurance instance, and the tests worked well!!!!
I even asked him to use the same email I was using, after the ##from tag, and that worked to.

So, could the problem be related to who makes de use of the tag?
Because with me it doesn't work, and with him it did.

And I have the Super-Admin profile :)

Regards,
André Petinga

**Comment by tomolimo** [comment]
Hello @andrepetinga 
Please could you upgrade to v2.1.0, this could solve your issue as I changed the way the email HTML bodies are decoded?
Now use Sanitizer::decodeHtmlSpecialChars().
Thank you,
Regards,
Tomolimo

**Comment by andrepetinga** [comment]
> Hello @andrepetinga
> Please could you upgrade to v2.1.0, this could solve your issue as I changed the way the email HTML bodies are decoded?
> Now use Sanitizer::decodeHtmlSpecialChars().
> Thank you,
> Regards,
> Tomolimo

Hello @tomolimo.
Just installed it on my Quality Assurance instance and it has an error when trying to download the emails:

``
[2024-11-21 14:36:03] glpiphplog.CRITICAL:   *** Uncaught Exception Error: Class "Sanitizer" not found in .../glpi/plugins/mailbehaviours/hook.php at line 84
  Backtrace :
  plugins/mailbehaviours/hook.php:105                PluginMailBehaviours::getTextFromHtml()
  plugins/mailbehaviours/hook.php:186                PluginMailBehaviours::getUsersID()
  src/Plugin.php:1713                                PluginMailBehaviours::plugin_pre_item_add_mailbehaviours()
  src/CommonDBTM.php:1300                            Plugin::doHook()
  src/MailCollector.php:897                          CommonDBTM->add()
  src/MailCollector.php:1923                         MailCollector->collect()
  src/CronTask.php:1027                              MailCollector::cronMailgate()
  front/cron.php:87                                  CronTask::launch()
``

**Comment by tomolimo** [comment]
Hello @andrepetinga 
Sorry for this bug...
Could you add this line `use Glpi\Toolbox\Sanitizer;`  at begin of file let's say line 29 (just before the `plugin_mailbehaviours_install` hook?
Like: 
![image](https://github.com/user-attachments/assets/81cdd40a-fdb4-49c3-a147-5c9073bb46c2)

Thank you
Regards,
Tomolimo

**Comment by andrepetinga** [comment]
> Hello @andrepetinga Sorry for this bug... Could you add this line `use Glpi\Toolbox\Sanitizer;` at begin of file let's say line 29 (just before the `plugin_mailbehaviours_install` hook? Like: ![image](https://private-user-images.githubusercontent.com/7569958/388844734-81cdd40a-fdb4-49c3-a147-5c9073bb46c2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyNzE5MDEsIm5iZiI6MTczMjI3MTYwMSwicGF0aCI6Ii83NTY5OTU4LzM4ODg0NDczNC04MWNkZDQwYS1mZGI0LTQ5YzMtYTE0Ny01YzkwNzNiYjQ2YzIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjJUMTAzMzIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjA0OTQ1MjY2MThlMmJlYWJmNWUyYjVmNDUzODMzMDA3YmNjMzU0MDcxOWZjOWZjZDY4OGIwYjBkMDZhYjkwNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.oyPXTTetH0APTmsm1O8N4dP_XXERctbXoE_7po_7vDM)
> 
> Thank you Regards, Tomolimo


Hello @tomolimo.

It works!!!!! 
Tested on both instances and it's working great!

Thanks!

Regards,
André Petinga

**Comment by tomolimo** [comment]
Ok, thank you, I'm going to prepare a new release with the fix
