### ISSUE TITLE
[1.0.2] When activated: got a blank screen

### ISSUE THREAD

**Issue by rubensaraiva10** [tomolimo/mailbehaviours#8]
Hello, I got some problems, I use Glpi with Ldpa, and my email enters but not for the correct user. I am using ##From: Test Test@test.com but is not working.

**Comment by tomolimo** [comment]
Hello @rubensaraiva10 

Not sure this an issue for this plugin...

Could you explain the root issue?
Is it as I understand an issue in your LDAP configuration?

Thank you

**Comment by rubensaraiva10** [comment]
I use now  GLPI 9.5.3 when I am using prefix ##From: Test <Test@test.com> my mailcollector doesn't work if I use it without "<>" don't assume any user. I was checking on the plugin and everything that he tries to search on DB is true. I don't know if I have done something wrong or I need to fix something to let it works

**Comment by tomolimo** [comment]
Hello @rubensaraiva10 

Default GLPI behavior is to use email sender as the ticket requester: you don't need to do anything about it...
You don't need to add any plugin for that.

Thank you
Regards,
Tomolimo

**Comment by rubensaraiva10** [comment]
But every time I try to send an email with the ##From: test, test<test@test.com> , my mailcollector don't work just open a blank page.

**Comment by tomolimo** [comment]
Hello @rubensaraiva10 
Could you detail the steps to reproduce this (with screencopies)?
Thank you
Regards,
Tomolimo

**Comment by rubensaraiva10** [comment]
![Unbenannt](https://user-images.githubusercontent.com/80674442/111126784-5fcdfb00-8573-11eb-8b46-865e1a62ead9.PNG)
![1](https://user-images.githubusercontent.com/80674442/111126787-5fcdfb00-8573-11eb-8b44-da715a0fecb3.PNG)

**Comment by tomolimo** [comment]
Hello @rubensaraiva10 
Thank you for the screencopies, but could you also describe steps by steps the issue, so that I can try to reproduce it?
Thank you
Regard,
Tomolimo

**Comment by rubensaraiva10** [comment]
So I want to use my Shop after someone Purchase to send one Ticket to my Glpi, on the body of my ticket will be an Email from a Customer that will create a Ticket with every information about it. The only thing that we do is, use a variable on my shop to add our email to that regex after we use Glpi to call that email and create a Ticket. When we enable that plugin I got that Blank screen if I disable will be a ticket created but not with a user that I want.

**Comment by tomolimo** [comment]
Hello @rubensaraiva10 
Could you post the error logs?
Thank you
Regards,
Tomolimo

**Comment by rubensaraiva10** [comment]
Now I check my email and every time that I use "<test@test.com>" in email cant be found. 


do we need "<>" to Plugin work?

**Comment by tomolimo** [comment]
Hello @rubensaraiva10
Could you post the error logs?
Thank you
Regards,
Tomolimo

**Comment by rubensaraiva10** [comment]
Let me find it and I will write them here

**Comment by tomolimo** [comment]
thank you

**Comment by rubensaraiva10** [comment]
on my mail.log I got not an error and on mail-error.log my last error was on 23.09.2020

**Comment by rubensaraiva10** [comment]
![image](https://user-images.githubusercontent.com/80674442/111131929-0d8fd880-8579-11eb-9bd6-67bae4b6f216.png)

**Comment by tomolimo** [comment]
Hello @rubensaraiva10 

Did you apply the fix like requested in the release comments?
Here: https://github.com/tomolimo/mailbehaviours/releases/tag/1.0.2

Thank you
Regards,
Tomolimo

**Comment by rubensaraiva10** [comment]
I have now applied the fix. But still not working. Now I don't get any blank page on mail collector and my email is created but still with the wrong user.
Logs von PHP under

![image](https://user-images.githubusercontent.com/80674442/111135755-534ea000-857d-11eb-86e7-7fa688bee1e6.png)

**Comment by tomolimo** [comment]
Hello @rubensaraiva10 
Could you explain the steps to reproduce the issue?
Could you post screenshots of the steps?
Thank you
Regards,
Tomolimo

**Comment by rubensaraiva10** [comment]
The step is the same. I sent an email and I load every email to get a ticket. But my ticket is not loaded with a user that I explicit on Tag ##From. I really don't do anything different. but every time I try to create an email with that plugin I get that error on my logs

**Comment by rubensaraiva10** [comment]
![image](https://user-images.githubusercontent.com/80674442/111161723-be0ed400-859b-11eb-8029-6c26f6621bd6.png)

**Comment by tomolimo** [comment]
Hello @rubensaraiva10
Could you post screenshots of the steps?
Thank you
Regards,
Tomolimo

**Comment by rubensaraiva10** [comment]
Hello @tomolimo, email i try with "<>" and without. But still don't find any user

![version](https://user-images.githubusercontent.com/80674442/111278587-ffee5780-8639-11eb-94eb-ef4e4027e96e.PNG)

![holen](https://user-images.githubusercontent.com/80674442/111278589-0086ee00-863a-11eb-979d-ffc1bd10c02b.PNG)
![ticket](https://user-images.githubusercontent.com/80674442/111278590-011f8480-863a-11eb-815a-a3da5b02f8f9.PNG)
![ticket1](https://user-images.githubusercontent.com/80674442/111278591-011f8480-863a-11eb-8ce6-448b1aa0d301.PNG)

**Comment by tomolimo** [comment]
Hello @rubensaraiva10 
Could you post the form of the user?
I need to check the user itself.
Thank you
Regard,
Tomolimo

**Comment by rubensaraiva10** [comment]
form? from email?

**Comment by tomolimo** [comment]
The user form in GLPI

**Comment by rubensaraiva10** [comment]
![userform](https://user-images.githubusercontent.com/80674442/111283109-0d5a1080-863f-11eb-9c7a-54e74b0bcf1e.PNG)

**Comment by rubensaraiva10** [comment]
Should I send you user.form.php?

**Comment by tomolimo** [comment]
Hello @rubensaraiva10 

I don't need the user.form.php (I have it already 😃)

I'm using a site to check the expression against the used regex in mailbehaviours
I've saved the regex along with the email of your user.
You could check that between name and email it needs a separation (like a comma, semi-column, column, gt,...), but not a space.
You may also use the <> around the email

Thank you,
Regards,
Tomolimo

**Comment by rubensaraiva10** [comment]
i will test it, thanks

**Comment by rubensaraiva10** [comment]
so i try like that ##from:test,test;<test.test@test.com>

Did you mean that right? 

i try like that but still didn't work

**Comment by tomolimo** [comment]
Hello @rubensaraiva10 
You may try like:
##from: first, last \<first.last@acme.com\> 
This **must** work

You may also try without the name, like:
##from: first.last@acme.com
This also **must** work

Thank you,
Regards,
Tomolimo

**Comment by tomolimo** [comment]
Hello @rubensaraiva10 
If none of these works, then I need the mail in EML file format, in order to try to reproduce on my PC.
Thank you
Regards,
Tomolimo

**Comment by rubensaraiva10** [comment]
I try both but still didn't work

**Comment by tomolimo** [comment]
I'll test this after lunch :)

**Comment by rubensaraiva10** [comment]
ok thanks a lot :)

**Comment by tomolimo** [comment]
Hello @rubensaraiva10,

I've made test with my 9.5.4 local release, and it passed OK.
1. I've added the user in my GLPI instance 
2. I've added to the email the \<\>, around the email of the user, that were missing in the eml file, I've encoded them like \&lt; and \&gt;
3. I've authorized "anonymous ticket creation" as I don't have the email sender in my GLPI users.
4. I've "got email tickets now" in my receiver.
5. the ticket has been created with the correct requester.

Here are some screencopies:

1. screencopy within Thunderbird of the modified eml file: 
![image](https://user-images.githubusercontent.com/7569958/111342668-f6d1aa80-867a-11eb-9951-7843ae5ddc49.png)
2. screencopy of the ticket: 
![image](https://user-images.githubusercontent.com/7569958/111343149-6f386b80-867b-11eb-8d90-db1ff649fc7f.png)

Thank you,
Regards,
Tomolimo

**Comment by tomolimo** [comment]
And screencopy of the modified eml file:

![image](https://user-images.githubusercontent.com/7569958/111343577-da823d80-867b-11eb-9965-8cf85dd3ac3a.png)

**Comment by rubensaraiva10** [comment]
I just try out but still can't create it with the right user, maybe I need to update my glpi to 9.5.4

**Comment by tomolimo** [comment]
It works also with 9.5.3

**Comment by rubensaraiva10** [comment]
![1](https://user-images.githubusercontent.com/80674442/111347170-3a2e1800-867f-11eb-8714-383fb636e022.PNG)

**Comment by tomolimo** [comment]
Let's try something else?
Are you ok if I ask you to modify the source code?
The idea is to add some logging infos in /plugins/mailbehaviours/hook.php
On line 83, could you add: `Toolbox::logInFile('mailbehaviours', $str);`
You should have something like:
![image](https://user-images.githubusercontent.com/7569958/111347216-44e8ad00-867f-11eb-9b50-58accd7f7ceb.png)

**Comment by tomolimo** [comment]
The test I made was with mailbehaviours as the only enabled plugin...

**Comment by rubensaraiva10** [comment]
I am using your Plugin 2.0 syntax is a little bit different

**Comment by tomolimo** [comment]
???

**Comment by tomolimo** [comment]
mailanalyzer doesn't have any longer the ##from feature inside...
You **must** use mailbehaviours for that

**Comment by rubensaraiva10** [comment]
I am really sorry, I didn't read the name of the file. let me fix that

**Comment by tomolimo** [comment]
And me, I didn't see that you were using the mailanalyzer for the ##from feature 😄

**Comment by tomolimo** [comment]
So start again the tests with the mailbehaviours plugin enabled 😃

**Comment by rubensaraiva10** [comment]
omg now works well.. I am really sorry. Thanks a lot for your patience. I will test it in the next few days but I am sure works well. do I need mail analyzer to work?

**Comment by tomolimo** [comment]
For the ##from feature, you don't need mailanalyzer.
Mailanalyzer purpose is to prevent duplicated tickets by adding followups to an existing ticket when received emails are from the same conversation.

**Comment by rubensaraiva10** [comment]
ok thanks a lot, and sorry again. Shame on me.

**Comment by tomolimo** [comment]
No problem, I should have better read the screencopies...

**Comment by rubensaraiva10** [comment]
> Tomolimo

Hello, can you please hide my email I forget to tell you yesterday, Thanks

everything works fine!

**Comment by tomolimo** [comment]
Hello @rubensaraiva10 
I believe it's ok now, could you check?

**Comment by rubensaraiva10** [comment]
yes, thanks :)
