### ISSUE TITLE
how to use the plugin?

### ISSUE THREAD

**Issue by juanzu** [tomolimo/mailbehaviours#9]
Hello how are you I am from Colombia and I am using a translator. I am trying to configure glpi to create tickets by mail. Investigating I found your plugin but I don't know how to use it. I have tried to put ## from and ## cc but no cases are created. Could you help me please

**Comment by tomolimo** [comment]
Hello @juanzu 
I'm going to prepare a wiki to explain how to use this plugin.
Thank you,
Regards,
Tomolimo

**Comment by tomolimo** [comment]
Hello @juanzu 
Wiki is under construction, you may consult it to already have a better idea on how to use this plugin.
[https://github.com/tomolimo/mailbehaviours/wiki](https://github.com/tomolimo/mailbehaviours/wiki)
Thank you
Regards,
Tomolimo
